In [2]:
from sklearn.datasets import fetch_20newsgroups
news = fetch_20newsgroups()

In [3]:
print(news.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [4]:
news.target

array([7, 4, 4, ..., 3, 1, 8])

In [5]:
news. target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [6]:
cats = ['alt.atheism', 'rec.sport.hockey','comp.graphics', 'sci.med']
news_train = fetch_20newsgroups(subset ='train', categories=cats)

In [7]:
news_test = fetch_20newsgroups(subset= 'test', categories=cats)

In [8]:
print(news_train . keys( ))
print (news_train[ 'target_names'])

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
['alt.atheism', 'comp.graphics', 'rec.sport.hockey', 'sci.med']


In [9]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect=CountVectorizer()
X_train_tf=count_vect.fit_transform(news_train.data)
print(X_train_tf)

X_train_tf.shape

  (0, 15388)	4
  (0, 16839)	1
  (0, 29282)	1
  (0, 35943)	1
  (0, 13204)	1
  (0, 32350)	2
  (0, 16845)	2
  (0, 31686)	2
  (0, 27601)	1
  (0, 31645)	3
  (0, 24383)	3
  (0, 7586)	5
  (0, 24245)	7
  (0, 22844)	5
  (0, 20822)	2
  (0, 2416)	2
  (0, 24553)	1
  (0, 35166)	2
  (0, 9751)	1
  (0, 18047)	3
  (0, 6093)	1
  (0, 3504)	1
  (0, 13634)	4
  (0, 22259)	4
  (0, 9423)	4
  :	:
  (2257, 18953)	1
  (2257, 35181)	1
  (2257, 26103)	1
  (2257, 6699)	1
  (2257, 34164)	1
  (2257, 27610)	1
  (2257, 4721)	1
  (2257, 27493)	1
  (2257, 19107)	1
  (2257, 6997)	2
  (2257, 9120)	1
  (2257, 35741)	1
  (2257, 25530)	1
  (2257, 880)	1
  (2257, 1142)	1
  (2257, 20948)	1
  (2257, 1400)	1
  (2257, 1999)	1
  (2257, 30975)	1
  (2257, 15026)	1
  (2257, 30437)	1
  (2257, 35272)	1
  (2257, 4706)	1
  (2257, 28332)	1
  (2257, 26100)	1


(2258, 36389)

In [10]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer()
X_train_tfidf=tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape

(2258, 36389)

In [11]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, news_train.target)

In [12]:
X_test_tf=count_vect.transform(news_test.data)
X_test_tfidf=tfidf_transformer.transform(X_test_tf)
predicted=clf.predict(X_test_tfidf)

predicted

array([2, 0, 2, ..., 0, 0, 1])

In [13]:
from sklearn import metrics

from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(news_test.target,predicted))
print(metrics.confusion_matrix(news_test.target,predicted))

Accuracy 0.9427811044577512
[[297   2   6  14]
 [  8 355   7  19]
 [  1   0 395   3]
 [  7  10   9 370]]
